//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.03 at 05:48:04 PM CET 
//


package ftn.xml.patent.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.jaxb.patent package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.jaxb.patent
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta }
     * 
     */
    public ZahtevZaPriznanjePatenta createZahtevZaPriznanjePatenta() {
        return new ZahtevZaPriznanjePatenta();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.PopunjavaPodnosioc.PrvobitnaPrijava }
     * 
     */
    public ZahtevZaPriznanjePatenta.PopunjavaPodnosioc.PrvobitnaPrijava createZahtevZaPriznanjePatentaPopunjavaPodnosiocPrvobitnaPrijava() {
        return new ZahtevZaPriznanjePatenta.PopunjavaPodnosioc.PrvobitnaPrijava();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.PopunjavaPodnosioc.PodaciOPronalazacu }
     * 
     */
    public ZahtevZaPriznanjePatenta.PopunjavaPodnosioc.PodaciOPronalazacu createZahtevZaPriznanjePatentaPopunjavaPodnosiocPodaciOPronalazacu() {
        return new ZahtevZaPriznanjePatenta.PopunjavaPodnosioc.PodaciOPronalazacu();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.Resenje }
     * 
     */
    public ZahtevZaPriznanjePatenta.Resenje createZahtevZaPriznanjePatentaResenje() {
        return new ZahtevZaPriznanjePatenta.Resenje();
    }

    /**
     * Create an instance of {@link Adresa }
     * 
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.PopunjavaPodnosioc.RanijePrijave }
     * 
     */
    public ZahtevZaPriznanjePatenta.PopunjavaPodnosioc.RanijePrijave createZahtevZaPriznanjePatentaPopunjavaPodnosiocRanijePrijave() {
        return new ZahtevZaPriznanjePatenta.PopunjavaPodnosioc.RanijePrijave();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.PriloziUzZahtev }
     * 
     */
    public ZahtevZaPriznanjePatenta.PriloziUzZahtev createZahtevZaPriznanjePatentaPriloziUzZahtev() {
        return new ZahtevZaPriznanjePatenta.PriloziUzZahtev();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.PopunjavaZavod }
     * 
     */
    public ZahtevZaPriznanjePatenta.PopunjavaZavod createZahtevZaPriznanjePatentaPopunjavaZavod() {
        return new ZahtevZaPriznanjePatenta.PopunjavaZavod();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.PopunjavaPodnosioc.NazivPatenta }
     * 
     */
    public ZahtevZaPriznanjePatenta.PopunjavaPodnosioc.NazivPatenta createZahtevZaPriznanjePatentaPopunjavaPodnosiocNazivPatenta() {
        return new ZahtevZaPriznanjePatenta.PopunjavaPodnosioc.NazivPatenta();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.PopunjavaPodnosioc }
     * 
     */
    public ZahtevZaPriznanjePatenta.PopunjavaPodnosioc createZahtevZaPriznanjePatentaPopunjavaPodnosioc() {
        return new ZahtevZaPriznanjePatenta.PopunjavaPodnosioc();
    }

    /**
     * Create an instance of {@link TEmpty }
     * 
     */
    public TEmpty createTEmpty() {
        return new TEmpty();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.PopunjavaPodnosioc.PodaciOPodnosiocu }
     * 
     */
    public ZahtevZaPriznanjePatenta.PopunjavaPodnosioc.PodaciOPodnosiocu createZahtevZaPriznanjePatentaPopunjavaPodnosiocPodaciOPodnosiocu() {
        return new ZahtevZaPriznanjePatenta.PopunjavaPodnosioc.PodaciOPodnosiocu();
    }

    /**
     * Create an instance of {@link Kontakt }
     * 
     */
    public Kontakt createKontakt() {
        return new Kontakt();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.InformacijeOUstanovi }
     * 
     */
    public ZahtevZaPriznanjePatenta.InformacijeOUstanovi createZahtevZaPriznanjePatentaInformacijeOUstanovi() {
        return new ZahtevZaPriznanjePatenta.InformacijeOUstanovi();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.PopunjavaPodnosioc.Dostavljanje }
     * 
     */
    public ZahtevZaPriznanjePatenta.PopunjavaPodnosioc.Dostavljanje createZahtevZaPriznanjePatentaPopunjavaPodnosiocDostavljanje() {
        return new ZahtevZaPriznanjePatenta.PopunjavaPodnosioc.Dostavljanje();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.PopunjavaPodnosioc.RanijePrijave.Prijava }
     * 
     */
    public ZahtevZaPriznanjePatenta.PopunjavaPodnosioc.RanijePrijave.Prijava createZahtevZaPriznanjePatentaPopunjavaPodnosiocRanijePrijavePrijava() {
        return new ZahtevZaPriznanjePatenta.PopunjavaPodnosioc.RanijePrijave.Prijava();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.PopunjavaPodnosioc.PodaciOPunomocniku.TipPunomocnika }
     * 
     */
    public ZahtevZaPriznanjePatenta.PopunjavaPodnosioc.PodaciOPunomocniku.TipPunomocnika createZahtevZaPriznanjePatentaPopunjavaPodnosiocPodaciOPunomocnikuTipPunomocnika() {
        return new ZahtevZaPriznanjePatenta.PopunjavaPodnosioc.PodaciOPunomocniku.TipPunomocnika();
    }

    /**
     * Create an instance of {@link TPoslovnoLice }
     * 
     */
    public TPoslovnoLice createTPoslovnoLice() {
        return new TPoslovnoLice();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta.PopunjavaPodnosioc.PodaciOPunomocniku }
     * 
     */
    public ZahtevZaPriznanjePatenta.PopunjavaPodnosioc.PodaciOPunomocniku createZahtevZaPriznanjePatentaPopunjavaPodnosiocPodaciOPunomocniku() {
        return new ZahtevZaPriznanjePatenta.PopunjavaPodnosioc.PodaciOPunomocniku();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

}
