//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.30 at 08:51:38 PM CET 
//


package ftn.xml.patent.model;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Informacije_o_ustanovi">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ftn.uns.ac.rs/jaxb/patent}Adresa"/>
 *                   &lt;element name="Naziv">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Popunjava_zavod">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Broj_prijave">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="P-[0-9]{5}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Datum_prijema">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Priznati_datum_podnosenja">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Popunjava_podnosioc">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Naziv_patenta">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Naziv_na_srpskom">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Naziv_na_engleskom">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Podaci_o_podnosiocu">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Podnosioc" type="{http://www.ftn.uns.ac.rs/jaxb/patent}TLice"/>
 *                             &lt;element name="Podnosioc_je_pronalazac" type="{http://www.ftn.uns.ac.rs/jaxb/patent}TEmpty" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Podaci_o_pronalazacu">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Pronalazac" type="{http://www.ftn.uns.ac.rs/jaxb/patent}TLice" maxOccurs="unbounded"/>
 *                             &lt;element name="Pronalazac_ne_zeli_da_bude_naveden" type="{http://www.ftn.uns.ac.rs/jaxb/patent}TEmpty" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Podaci_o_punomocniku">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Punomocnik" type="{http://www.ftn.uns.ac.rs/jaxb/patent}TLice"/>
 *                             &lt;element name="Tip_punomocnika">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Za_zastupanje" type="{http://www.ftn.uns.ac.rs/jaxb/patent}TEmpty" minOccurs="0"/>
 *                                       &lt;element name="Za_prijem" type="{http://www.ftn.uns.ac.rs/jaxb/patent}TEmpty" minOccurs="0"/>
 *                                       &lt;element name="Predstavnik" type="{http://www.ftn.uns.ac.rs/jaxb/patent}TEmpty" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Dostavljanje">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://www.ftn.uns.ac.rs/jaxb/patent}Adresa"/>
 *                             &lt;element name="Nacin">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="elektronski"/>
 *                                   &lt;enumeration value="pisano"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Prvobitna_prijava">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Broj_prijave">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Datum_podnosenja">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Tip_prijave">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="izdvojena"/>
 *                                   &lt;enumeration value="dopunska"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Ranije_prijave">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Prijava" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Broj_prijave">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="Datum_podnosenja">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="Dvoslovna_oznaka">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;length value="2"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Prilozi_uz_zahtev">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Prva_prijava" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Ranija_prijava" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Izjava_o_osnovu_sticanja_prava_na_podnosenje_prijave" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Izjava_pronalazaca_da_ne_zeli_da_bude_naveden" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Opis_pronalaska" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Patentni_zahtevi_za_zastitu_pronalaska" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                   &lt;element name="Nacrt_na_koji_se_poziva_opis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Apstrakt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Resenje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Resenje" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Datum" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="Status">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Odobren"/>
 *                         &lt;enumeration value="Odbijen"/>
 *                         &lt;enumeration value=""/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Ime">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Prezime">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Broj_prijave" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Referenca_na_zahtev" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Obrazlozenje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "informacijeOUstanovi",
    "popunjavaZavod",
    "popunjavaPodnosioc",
    "priloziUzZahtev",
    "resenje"
})
@XmlRootElement(name = "Zahtev_za_priznanje_patenta")
public class ZahtevZaPriznanjePatenta {

    @XmlElement(name = "Informacije_o_ustanovi", required = true)
    protected InformacijeOUstanovi informacijeOUstanovi;
    @XmlElement(name = "Popunjava_zavod", required = true)
    protected PopunjavaZavod popunjavaZavod;
    @XmlElement(name = "Popunjava_podnosioc", required = true)
    protected PopunjavaPodnosioc popunjavaPodnosioc;
    @XmlElement(name = "Prilozi_uz_zahtev", required = true)
    protected PriloziUzZahtev priloziUzZahtev;
    @XmlElement(name = "Resenje")
    protected Resenje resenje;

    /**
     * Gets the value of the informacijeOUstanovi property.
     * 
     * @return
     *     possible object is
     *     {@link InformacijeOUstanovi }
     *     
     */
    public InformacijeOUstanovi getInformacijeOUstanovi() {
        return informacijeOUstanovi;
    }

    /**
     * Sets the value of the informacijeOUstanovi property.
     * 
     * @param value
     *     allowed object is
     *     {@link InformacijeOUstanovi }
     *     
     */
    public void setInformacijeOUstanovi(InformacijeOUstanovi value) {
        this.informacijeOUstanovi = value;
    }

    /**
     * Gets the value of the popunjavaZavod property.
     * 
     * @return
     *     possible object is
     *     {@link PopunjavaZavod }
     *     
     */
    public PopunjavaZavod getPopunjavaZavod() {
        return popunjavaZavod;
    }

    /**
     * Sets the value of the popunjavaZavod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PopunjavaZavod }
     *     
     */
    public void setPopunjavaZavod(PopunjavaZavod value) {
        this.popunjavaZavod = value;
    }

    /**
     * Gets the value of the popunjavaPodnosioc property.
     * 
     * @return
     *     possible object is
     *     {@link PopunjavaPodnosioc }
     *     
     */
    public PopunjavaPodnosioc getPopunjavaPodnosioc() {
        return popunjavaPodnosioc;
    }

    /**
     * Sets the value of the popunjavaPodnosioc property.
     * 
     * @param value
     *     allowed object is
     *     {@link PopunjavaPodnosioc }
     *     
     */
    public void setPopunjavaPodnosioc(PopunjavaPodnosioc value) {
        this.popunjavaPodnosioc = value;
    }

    /**
     * Gets the value of the priloziUzZahtev property.
     * 
     * @return
     *     possible object is
     *     {@link PriloziUzZahtev }
     *     
     */
    public PriloziUzZahtev getPriloziUzZahtev() {
        return priloziUzZahtev;
    }

    /**
     * Sets the value of the priloziUzZahtev property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriloziUzZahtev }
     *     
     */
    public void setPriloziUzZahtev(PriloziUzZahtev value) {
        this.priloziUzZahtev = value;
    }

    /**
     * Gets the value of the resenje property.
     * 
     * @return
     *     possible object is
     *     {@link Resenje }
     *     
     */
    public Resenje getResenje() {
        return resenje;
    }

    /**
     * Sets the value of the resenje property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resenje }
     *     
     */
    public void setResenje(Resenje value) {
        this.resenje = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ftn.uns.ac.rs/jaxb/patent}Adresa"/>
     *         &lt;element name="Naziv">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "adresa",
        "naziv"
    })
    public static class InformacijeOUstanovi {

        @XmlElement(name = "Adresa", required = true)
        protected Adresa adresa;
        @XmlElement(name = "Naziv", required = true)
        protected String naziv;

        /**
         * Gets the value of the adresa property.
         * 
         * @return
         *     possible object is
         *     {@link Adresa }
         *     
         */
        public Adresa getAdresa() {
            return adresa;
        }

        /**
         * Sets the value of the adresa property.
         * 
         * @param value
         *     allowed object is
         *     {@link Adresa }
         *     
         */
        public void setAdresa(Adresa value) {
            this.adresa = value;
        }

        /**
         * Gets the value of the naziv property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaziv() {
            return naziv;
        }

        /**
         * Sets the value of the naziv property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaziv(String value) {
            this.naziv = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Naziv_patenta">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Naziv_na_srpskom">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Naziv_na_engleskom">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Podaci_o_podnosiocu">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Podnosioc" type="{http://www.ftn.uns.ac.rs/jaxb/patent}TLice"/>
     *                   &lt;element name="Podnosioc_je_pronalazac" type="{http://www.ftn.uns.ac.rs/jaxb/patent}TEmpty" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Podaci_o_pronalazacu">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Pronalazac" type="{http://www.ftn.uns.ac.rs/jaxb/patent}TLice" maxOccurs="unbounded"/>
     *                   &lt;element name="Pronalazac_ne_zeli_da_bude_naveden" type="{http://www.ftn.uns.ac.rs/jaxb/patent}TEmpty" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Podaci_o_punomocniku">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Punomocnik" type="{http://www.ftn.uns.ac.rs/jaxb/patent}TLice"/>
     *                   &lt;element name="Tip_punomocnika">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Za_zastupanje" type="{http://www.ftn.uns.ac.rs/jaxb/patent}TEmpty" minOccurs="0"/>
     *                             &lt;element name="Za_prijem" type="{http://www.ftn.uns.ac.rs/jaxb/patent}TEmpty" minOccurs="0"/>
     *                             &lt;element name="Predstavnik" type="{http://www.ftn.uns.ac.rs/jaxb/patent}TEmpty" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Dostavljanje">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://www.ftn.uns.ac.rs/jaxb/patent}Adresa"/>
     *                   &lt;element name="Nacin">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="elektronski"/>
     *                         &lt;enumeration value="pisano"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Prvobitna_prijava">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Broj_prijave">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Datum_podnosenja">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Tip_prijave">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="izdvojena"/>
     *                         &lt;enumeration value="dopunska"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Ranije_prijave">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Prijava" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Broj_prijave">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="Datum_podnosenja">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="Dvoslovna_oznaka">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;length value="2"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nazivPatenta",
        "podaciOPodnosiocu",
        "podaciOPronalazacu",
        "podaciOPunomocniku",
        "dostavljanje",
        "prvobitnaPrijava",
        "ranijePrijave"
    })
    public static class PopunjavaPodnosioc {

        @XmlElement(name = "Naziv_patenta", required = true)
        protected NazivPatenta nazivPatenta;
        @XmlElement(name = "Podaci_o_podnosiocu", required = true)
        protected PodaciOPodnosiocu podaciOPodnosiocu;
        @XmlElement(name = "Podaci_o_pronalazacu", required = true)
        protected PodaciOPronalazacu podaciOPronalazacu;
        @XmlElement(name = "Podaci_o_punomocniku", required = true)
        protected PodaciOPunomocniku podaciOPunomocniku;
        @XmlElement(name = "Dostavljanje", required = true)
        protected Dostavljanje dostavljanje;
        @XmlElement(name = "Prvobitna_prijava", required = true)
        protected PrvobitnaPrijava prvobitnaPrijava;
        @XmlElement(name = "Ranije_prijave", required = true)
        protected RanijePrijave ranijePrijave;

        /**
         * Gets the value of the nazivPatenta property.
         * 
         * @return
         *     possible object is
         *     {@link NazivPatenta }
         *     
         */
        public NazivPatenta getNazivPatenta() {
            return nazivPatenta;
        }

        /**
         * Sets the value of the nazivPatenta property.
         * 
         * @param value
         *     allowed object is
         *     {@link NazivPatenta }
         *     
         */
        public void setNazivPatenta(NazivPatenta value) {
            this.nazivPatenta = value;
        }

        /**
         * Gets the value of the podaciOPodnosiocu property.
         * 
         * @return
         *     possible object is
         *     {@link PodaciOPodnosiocu }
         *     
         */
        public PodaciOPodnosiocu getPodaciOPodnosiocu() {
            return podaciOPodnosiocu;
        }

        /**
         * Sets the value of the podaciOPodnosiocu property.
         * 
         * @param value
         *     allowed object is
         *     {@link PodaciOPodnosiocu }
         *     
         */
        public void setPodaciOPodnosiocu(PodaciOPodnosiocu value) {
            this.podaciOPodnosiocu = value;
        }

        /**
         * Gets the value of the podaciOPronalazacu property.
         * 
         * @return
         *     possible object is
         *     {@link PodaciOPronalazacu }
         *     
         */
        public PodaciOPronalazacu getPodaciOPronalazacu() {
            return podaciOPronalazacu;
        }

        /**
         * Sets the value of the podaciOPronalazacu property.
         * 
         * @param value
         *     allowed object is
         *     {@link PodaciOPronalazacu }
         *     
         */
        public void setPodaciOPronalazacu(PodaciOPronalazacu value) {
            this.podaciOPronalazacu = value;
        }

        /**
         * Gets the value of the podaciOPunomocniku property.
         * 
         * @return
         *     possible object is
         *     {@link PodaciOPunomocniku }
         *     
         */
        public PodaciOPunomocniku getPodaciOPunomocniku() {
            return podaciOPunomocniku;
        }

        /**
         * Sets the value of the podaciOPunomocniku property.
         * 
         * @param value
         *     allowed object is
         *     {@link PodaciOPunomocniku }
         *     
         */
        public void setPodaciOPunomocniku(PodaciOPunomocniku value) {
            this.podaciOPunomocniku = value;
        }

        /**
         * Gets the value of the dostavljanje property.
         * 
         * @return
         *     possible object is
         *     {@link Dostavljanje }
         *     
         */
        public Dostavljanje getDostavljanje() {
            return dostavljanje;
        }

        /**
         * Sets the value of the dostavljanje property.
         * 
         * @param value
         *     allowed object is
         *     {@link Dostavljanje }
         *     
         */
        public void setDostavljanje(Dostavljanje value) {
            this.dostavljanje = value;
        }

        /**
         * Gets the value of the prvobitnaPrijava property.
         * 
         * @return
         *     possible object is
         *     {@link PrvobitnaPrijava }
         *     
         */
        public PrvobitnaPrijava getPrvobitnaPrijava() {
            return prvobitnaPrijava;
        }

        /**
         * Sets the value of the prvobitnaPrijava property.
         * 
         * @param value
         *     allowed object is
         *     {@link PrvobitnaPrijava }
         *     
         */
        public void setPrvobitnaPrijava(PrvobitnaPrijava value) {
            this.prvobitnaPrijava = value;
        }

        /**
         * Gets the value of the ranijePrijave property.
         * 
         * @return
         *     possible object is
         *     {@link RanijePrijave }
         *     
         */
        public RanijePrijave getRanijePrijave() {
            return ranijePrijave;
        }

        /**
         * Sets the value of the ranijePrijave property.
         * 
         * @param value
         *     allowed object is
         *     {@link RanijePrijave }
         *     
         */
        public void setRanijePrijave(RanijePrijave value) {
            this.ranijePrijave = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.ftn.uns.ac.rs/jaxb/patent}Adresa"/>
         *         &lt;element name="Nacin">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="elektronski"/>
         *               &lt;enumeration value="pisano"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "adresa",
            "nacin"
        })
        public static class Dostavljanje {

            @XmlElement(name = "Adresa", required = true)
            protected Adresa adresa;
            @XmlElement(name = "Nacin", required = true)
            protected String nacin;

            /**
             * Gets the value of the adresa property.
             * 
             * @return
             *     possible object is
             *     {@link Adresa }
             *     
             */
            public Adresa getAdresa() {
                return adresa;
            }

            /**
             * Sets the value of the adresa property.
             * 
             * @param value
             *     allowed object is
             *     {@link Adresa }
             *     
             */
            public void setAdresa(Adresa value) {
                this.adresa = value;
            }

            /**
             * Gets the value of the nacin property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNacin() {
                return nacin;
            }

            /**
             * Sets the value of the nacin property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNacin(String value) {
                this.nacin = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Naziv_na_srpskom">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Naziv_na_engleskom">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nazivNaSrpskom",
            "nazivNaEngleskom"
        })
        public static class NazivPatenta {

            @XmlElement(name = "Naziv_na_srpskom", required = true)
            protected String nazivNaSrpskom;
            @XmlElement(name = "Naziv_na_engleskom", required = true)
            protected String nazivNaEngleskom;

            /**
             * Gets the value of the nazivNaSrpskom property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNazivNaSrpskom() {
                return nazivNaSrpskom;
            }

            /**
             * Sets the value of the nazivNaSrpskom property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNazivNaSrpskom(String value) {
                this.nazivNaSrpskom = value;
            }

            /**
             * Gets the value of the nazivNaEngleskom property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNazivNaEngleskom() {
                return nazivNaEngleskom;
            }

            /**
             * Sets the value of the nazivNaEngleskom property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNazivNaEngleskom(String value) {
                this.nazivNaEngleskom = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Podnosioc" type="{http://www.ftn.uns.ac.rs/jaxb/patent}TLice"/>
         *         &lt;element name="Podnosioc_je_pronalazac" type="{http://www.ftn.uns.ac.rs/jaxb/patent}TEmpty" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "podnosioc",
            "podnosiocJePronalazac"
        })
        public static class PodaciOPodnosiocu {

            @XmlElement(name = "Podnosioc", required = true)
            protected TLice podnosioc;
            @XmlElement(name = "Podnosioc_je_pronalazac")
            protected TEmpty podnosiocJePronalazac;

            /**
             * Gets the value of the podnosioc property.
             * 
             * @return
             *     possible object is
             *     {@link TLice }
             *     
             */
            public TLice getPodnosioc() {
                return podnosioc;
            }

            /**
             * Sets the value of the podnosioc property.
             * 
             * @param value
             *     allowed object is
             *     {@link TLice }
             *     
             */
            public void setPodnosioc(TLice value) {
                this.podnosioc = value;
            }

            /**
             * Gets the value of the podnosiocJePronalazac property.
             * 
             * @return
             *     possible object is
             *     {@link TEmpty }
             *     
             */
            public TEmpty getPodnosiocJePronalazac() {
                return podnosiocJePronalazac;
            }

            /**
             * Sets the value of the podnosiocJePronalazac property.
             * 
             * @param value
             *     allowed object is
             *     {@link TEmpty }
             *     
             */
            public void setPodnosiocJePronalazac(TEmpty value) {
                this.podnosiocJePronalazac = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Pronalazac" type="{http://www.ftn.uns.ac.rs/jaxb/patent}TLice" maxOccurs="unbounded"/>
         *         &lt;element name="Pronalazac_ne_zeli_da_bude_naveden" type="{http://www.ftn.uns.ac.rs/jaxb/patent}TEmpty" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "pronalazac",
            "pronalazacNeZeliDaBudeNaveden"
        })
        public static class PodaciOPronalazacu {

            @XmlElement(name = "Pronalazac", required = true)
            protected List<TLice> pronalazac;
            @XmlElement(name = "Pronalazac_ne_zeli_da_bude_naveden")
            protected TEmpty pronalazacNeZeliDaBudeNaveden;

            /**
             * Gets the value of the pronalazac property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the pronalazac property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPronalazac().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TLice }
             * 
             * 
             */
            public List<TLice> getPronalazac() {
                if (pronalazac == null) {
                    pronalazac = new ArrayList<TLice>();
                }
                return this.pronalazac;
            }

            /**
             * Gets the value of the pronalazacNeZeliDaBudeNaveden property.
             * 
             * @return
             *     possible object is
             *     {@link TEmpty }
             *     
             */
            public TEmpty getPronalazacNeZeliDaBudeNaveden() {
                return pronalazacNeZeliDaBudeNaveden;
            }

            /**
             * Sets the value of the pronalazacNeZeliDaBudeNaveden property.
             * 
             * @param value
             *     allowed object is
             *     {@link TEmpty }
             *     
             */
            public void setPronalazacNeZeliDaBudeNaveden(TEmpty value) {
                this.pronalazacNeZeliDaBudeNaveden = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Punomocnik" type="{http://www.ftn.uns.ac.rs/jaxb/patent}TLice"/>
         *         &lt;element name="Tip_punomocnika">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Za_zastupanje" type="{http://www.ftn.uns.ac.rs/jaxb/patent}TEmpty" minOccurs="0"/>
         *                   &lt;element name="Za_prijem" type="{http://www.ftn.uns.ac.rs/jaxb/patent}TEmpty" minOccurs="0"/>
         *                   &lt;element name="Predstavnik" type="{http://www.ftn.uns.ac.rs/jaxb/patent}TEmpty" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "punomocnik",
            "tipPunomocnika"
        })
        public static class PodaciOPunomocniku {

            @XmlElement(name = "Punomocnik", required = true)
            protected TLice punomocnik;
            @XmlElement(name = "Tip_punomocnika", required = true)
            protected TipPunomocnika tipPunomocnika;

            /**
             * Gets the value of the punomocnik property.
             * 
             * @return
             *     possible object is
             *     {@link TLice }
             *     
             */
            public TLice getPunomocnik() {
                return punomocnik;
            }

            /**
             * Sets the value of the punomocnik property.
             * 
             * @param value
             *     allowed object is
             *     {@link TLice }
             *     
             */
            public void setPunomocnik(TLice value) {
                this.punomocnik = value;
            }

            /**
             * Gets the value of the tipPunomocnika property.
             * 
             * @return
             *     possible object is
             *     {@link TipPunomocnika }
             *     
             */
            public TipPunomocnika getTipPunomocnika() {
                return tipPunomocnika;
            }

            /**
             * Sets the value of the tipPunomocnika property.
             * 
             * @param value
             *     allowed object is
             *     {@link TipPunomocnika }
             *     
             */
            public void setTipPunomocnika(TipPunomocnika value) {
                this.tipPunomocnika = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Za_zastupanje" type="{http://www.ftn.uns.ac.rs/jaxb/patent}TEmpty" minOccurs="0"/>
             *         &lt;element name="Za_prijem" type="{http://www.ftn.uns.ac.rs/jaxb/patent}TEmpty" minOccurs="0"/>
             *         &lt;element name="Predstavnik" type="{http://www.ftn.uns.ac.rs/jaxb/patent}TEmpty" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "zaZastupanje",
                "zaPrijem",
                "predstavnik"
            })
            public static class TipPunomocnika {

                @XmlElement(name = "Za_zastupanje")
                protected TEmpty zaZastupanje;
                @XmlElement(name = "Za_prijem")
                protected TEmpty zaPrijem;
                @XmlElement(name = "Predstavnik")
                protected TEmpty predstavnik;

                /**
                 * Gets the value of the zaZastupanje property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TEmpty }
                 *     
                 */
                public TEmpty getZaZastupanje() {
                    return zaZastupanje;
                }

                /**
                 * Sets the value of the zaZastupanje property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TEmpty }
                 *     
                 */
                public void setZaZastupanje(TEmpty value) {
                    this.zaZastupanje = value;
                }

                /**
                 * Gets the value of the zaPrijem property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TEmpty }
                 *     
                 */
                public TEmpty getZaPrijem() {
                    return zaPrijem;
                }

                /**
                 * Sets the value of the zaPrijem property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TEmpty }
                 *     
                 */
                public void setZaPrijem(TEmpty value) {
                    this.zaPrijem = value;
                }

                /**
                 * Gets the value of the predstavnik property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TEmpty }
                 *     
                 */
                public TEmpty getPredstavnik() {
                    return predstavnik;
                }

                /**
                 * Sets the value of the predstavnik property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TEmpty }
                 *     
                 */
                public void setPredstavnik(TEmpty value) {
                    this.predstavnik = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Broj_prijave">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Datum_podnosenja">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Tip_prijave">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="izdvojena"/>
         *               &lt;enumeration value="dopunska"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "brojPrijave",
            "datumPodnosenja",
            "tipPrijave"
        })
        public static class PrvobitnaPrijava {

            @XmlElement(name = "Broj_prijave", required = true)
            protected String brojPrijave;
            @XmlElement(name = "Datum_podnosenja", required = true)
            protected XMLGregorianCalendar datumPodnosenja;
            @XmlElement(name = "Tip_prijave", required = true)
            protected String tipPrijave;

            /**
             * Gets the value of the brojPrijave property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBrojPrijave() {
                return brojPrijave;
            }

            /**
             * Sets the value of the brojPrijave property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBrojPrijave(String value) {
                this.brojPrijave = value;
            }

            /**
             * Gets the value of the datumPodnosenja property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDatumPodnosenja() {
                return datumPodnosenja;
            }

            /**
             * Sets the value of the datumPodnosenja property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDatumPodnosenja(XMLGregorianCalendar value) {
                this.datumPodnosenja = value;
            }

            /**
             * Gets the value of the tipPrijave property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTipPrijave() {
                return tipPrijave;
            }

            /**
             * Sets the value of the tipPrijave property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTipPrijave(String value) {
                this.tipPrijave = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Prijava" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Broj_prijave">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="Datum_podnosenja">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="Dvoslovna_oznaka">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;length value="2"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "prijava"
        })
        public static class RanijePrijave {

            @XmlElement(name = "Prijava")
            protected List<Prijava> prijava;

            /**
             * Gets the value of the prijava property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the prijava property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPrijava().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Prijava }
             * 
             * 
             */
            public List<Prijava> getPrijava() {
                if (prijava == null) {
                    prijava = new ArrayList<Prijava>();
                }
                return this.prijava;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Broj_prijave">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="Datum_podnosenja">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="Dvoslovna_oznaka">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;length value="2"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "brojPrijave",
                "datumPodnosenja",
                "dvoslovnaOznaka"
            })
            public static class Prijava {

                @XmlElement(name = "Broj_prijave", required = true)
                protected String brojPrijave;
                @XmlElement(name = "Datum_podnosenja", required = true)
                protected XMLGregorianCalendar datumPodnosenja;
                @XmlElement(name = "Dvoslovna_oznaka", required = true)
                protected String dvoslovnaOznaka;

                /**
                 * Gets the value of the brojPrijave property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getBrojPrijave() {
                    return brojPrijave;
                }

                /**
                 * Sets the value of the brojPrijave property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setBrojPrijave(String value) {
                    this.brojPrijave = value;
                }

                /**
                 * Gets the value of the datumPodnosenja property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getDatumPodnosenja() {
                    return datumPodnosenja;
                }

                /**
                 * Sets the value of the datumPodnosenja property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setDatumPodnosenja(XMLGregorianCalendar value) {
                    this.datumPodnosenja = value;
                }

                /**
                 * Gets the value of the dvoslovnaOznaka property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDvoslovnaOznaka() {
                    return dvoslovnaOznaka;
                }

                /**
                 * Sets the value of the dvoslovnaOznaka property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDvoslovnaOznaka(String value) {
                    this.dvoslovnaOznaka = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Broj_prijave">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="P-[0-9]{5}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Datum_prijema">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Priznati_datum_podnosenja">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "brojPrijave",
        "datumPrijema",
        "priznatiDatumPodnosenja"
    })
    public static class PopunjavaZavod {

        @XmlElement(name = "Broj_prijave", required = true)
        protected String brojPrijave;
        @XmlElement(name = "Datum_prijema", required = true)
        protected XMLGregorianCalendar datumPrijema;
        @XmlElement(name = "Priznati_datum_podnosenja", required = true)
        protected XMLGregorianCalendar priznatiDatumPodnosenja;

        /**
         * Gets the value of the brojPrijave property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBrojPrijave() {
            return brojPrijave;
        }

        /**
         * Sets the value of the brojPrijave property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrojPrijave(String value) {
            this.brojPrijave = value;
        }

        /**
         * Gets the value of the datumPrijema property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumPrijema() {
            return datumPrijema;
        }

        /**
         * Sets the value of the datumPrijema property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumPrijema(XMLGregorianCalendar value) {
            this.datumPrijema = value;
        }

        /**
         * Gets the value of the priznatiDatumPodnosenja property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getPriznatiDatumPodnosenja() {
            return priznatiDatumPodnosenja;
        }

        /**
         * Sets the value of the priznatiDatumPodnosenja property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setPriznatiDatumPodnosenja(XMLGregorianCalendar value) {
            this.priznatiDatumPodnosenja = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Prva_prijava" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Ranija_prijava" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="Izjava_o_osnovu_sticanja_prava_na_podnosenje_prijave" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Izjava_pronalazaca_da_ne_zeli_da_bude_naveden" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Opis_pronalaska" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Patentni_zahtevi_za_zastitu_pronalaska" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *         &lt;element name="Nacrt_na_koji_se_poziva_opis" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Apstrakt" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Resenje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "prvaPrijava",
        "ranijaPrijava",
        "izjavaOOsnovuSticanjaPravaNaPodnosenjePrijave",
        "izjavaPronalazacaDaNeZeliDaBudeNaveden",
        "opisPronalaska",
        "patentniZahteviZaZastituPronalaska",
        "nacrtNaKojiSePozivaOpis",
        "apstrakt",
        "resenje"
    })
    public static class PriloziUzZahtev {

        @XmlElement(name = "Prva_prijava")
        protected String prvaPrijava;
        @XmlElement(name = "Ranija_prijava")
        protected List<String> ranijaPrijava;
        @XmlElement(name = "Izjava_o_osnovu_sticanja_prava_na_podnosenje_prijave")
        protected String izjavaOOsnovuSticanjaPravaNaPodnosenjePrijave;
        @XmlElement(name = "Izjava_pronalazaca_da_ne_zeli_da_bude_naveden")
        protected String izjavaPronalazacaDaNeZeliDaBudeNaveden;
        @XmlElement(name = "Opis_pronalaska", required = true)
        protected String opisPronalaska;
        @XmlElement(name = "Patentni_zahtevi_za_zastitu_pronalaska", required = true)
        protected List<String> patentniZahteviZaZastituPronalaska;
        @XmlElement(name = "Nacrt_na_koji_se_poziva_opis", required = true)
        protected String nacrtNaKojiSePozivaOpis;
        @XmlElement(name = "Apstrakt", required = true)
        protected String apstrakt;
        @XmlElement(name = "Resenje")
        protected String resenje;

        /**
         * Gets the value of the prvaPrijava property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrvaPrijava() {
            return prvaPrijava;
        }

        /**
         * Sets the value of the prvaPrijava property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrvaPrijava(String value) {
            this.prvaPrijava = value;
        }

        /**
         * Gets the value of the ranijaPrijava property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ranijaPrijava property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRanijaPrijava().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getRanijaPrijava() {
            if (ranijaPrijava == null) {
                ranijaPrijava = new ArrayList<String>();
            }
            return this.ranijaPrijava;
        }

        /**
         * Gets the value of the izjavaOOsnovuSticanjaPravaNaPodnosenjePrijave property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIzjavaOOsnovuSticanjaPravaNaPodnosenjePrijave() {
            return izjavaOOsnovuSticanjaPravaNaPodnosenjePrijave;
        }

        /**
         * Sets the value of the izjavaOOsnovuSticanjaPravaNaPodnosenjePrijave property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIzjavaOOsnovuSticanjaPravaNaPodnosenjePrijave(String value) {
            this.izjavaOOsnovuSticanjaPravaNaPodnosenjePrijave = value;
        }

        /**
         * Gets the value of the izjavaPronalazacaDaNeZeliDaBudeNaveden property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIzjavaPronalazacaDaNeZeliDaBudeNaveden() {
            return izjavaPronalazacaDaNeZeliDaBudeNaveden;
        }

        /**
         * Sets the value of the izjavaPronalazacaDaNeZeliDaBudeNaveden property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIzjavaPronalazacaDaNeZeliDaBudeNaveden(String value) {
            this.izjavaPronalazacaDaNeZeliDaBudeNaveden = value;
        }

        /**
         * Gets the value of the opisPronalaska property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOpisPronalaska() {
            return opisPronalaska;
        }

        /**
         * Sets the value of the opisPronalaska property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOpisPronalaska(String value) {
            this.opisPronalaska = value;
        }

        /**
         * Gets the value of the patentniZahteviZaZastituPronalaska property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the patentniZahteviZaZastituPronalaska property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPatentniZahteviZaZastituPronalaska().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getPatentniZahteviZaZastituPronalaska() {
            if (patentniZahteviZaZastituPronalaska == null) {
                patentniZahteviZaZastituPronalaska = new ArrayList<String>();
            }
            return this.patentniZahteviZaZastituPronalaska;
        }

        /**
         * Gets the value of the nacrtNaKojiSePozivaOpis property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNacrtNaKojiSePozivaOpis() {
            return nacrtNaKojiSePozivaOpis;
        }

        /**
         * Sets the value of the nacrtNaKojiSePozivaOpis property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNacrtNaKojiSePozivaOpis(String value) {
            this.nacrtNaKojiSePozivaOpis = value;
        }

        /**
         * Gets the value of the apstrakt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApstrakt() {
            return apstrakt;
        }

        /**
         * Sets the value of the apstrakt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApstrakt(String value) {
            this.apstrakt = value;
        }

        /**
         * Gets the value of the resenje property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResenje() {
            return resenje;
        }

        /**
         * Sets the value of the resenje property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResenje(String value) {
            this.resenje = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Datum" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="Status">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Odobren"/>
     *               &lt;enumeration value="Odbijen"/>
     *               &lt;enumeration value=""/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Ime">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Prezime">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Broj_prijave" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Referenca_na_zahtev" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Obrazlozenje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "datum",
        "status",
        "ime",
        "prezime",
        "brojPrijave",
        "referencaNaZahtev",
        "obrazlozenje"
    })
    public static class Resenje {

        @XmlElement(name = "Datum", required = true)
        protected XMLGregorianCalendar datum;
        @XmlElement(name = "Status", required = true)
        protected String status;
        @XmlElement(name = "Ime", required = true)
        protected String ime;
        @XmlElement(name = "Prezime", required = true)
        protected String prezime;
        @XmlElement(name = "Broj_prijave", required = true)
        protected String brojPrijave;
        @XmlElement(name = "Referenca_na_zahtev", required = true)
        protected String referencaNaZahtev;
        @XmlElement(name = "Obrazlozenje")
        protected String obrazlozenje;

        /**
         * Gets the value of the datum property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatum() {
            return datum;
        }

        /**
         * Sets the value of the datum property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatum(XMLGregorianCalendar value) {
            this.datum = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the ime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIme() {
            return ime;
        }

        /**
         * Sets the value of the ime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIme(String value) {
            this.ime = value;
        }

        /**
         * Gets the value of the prezime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrezime() {
            return prezime;
        }

        /**
         * Sets the value of the prezime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrezime(String value) {
            this.prezime = value;
        }

        /**
         * Gets the value of the brojPrijave property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBrojPrijave() {
            return brojPrijave;
        }

        /**
         * Sets the value of the brojPrijave property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrojPrijave(String value) {
            this.brojPrijave = value;
        }

        /**
         * Gets the value of the referencaNaZahtev property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReferencaNaZahtev() {
            return referencaNaZahtev;
        }

        /**
         * Sets the value of the referencaNaZahtev property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReferencaNaZahtev(String value) {
            this.referencaNaZahtev = value;
        }

        /**
         * Gets the value of the obrazlozenje property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getObrazlozenje() {
            return obrazlozenje;
        }

        /**
         * Sets the value of the obrazlozenje property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setObrazlozenje(String value) {
            this.obrazlozenje = value;
        }

    }

}
