//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.20 at 11:54:02 AM CET 
//


package ftn.xml.korisnik.model;

import ftn.xml.korisnik.dto.RegistrationDTO;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Ime">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Prezime">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Email">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="[\w\-\.]+@([\w\-]+\.)+[\w\-]{2,4}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Sifra" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Uloga">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="Gradjanin|Sluzbenik"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/jaxb/korisnik}Adresa"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "ime",
        "prezime",
        "email",
        "sifra",
        "uloga",
        "adresa"
})
@XmlRootElement(name = "Korisnik")
public class Korisnik {

    @XmlElement(name = "Ime", required = true)
    protected String ime;
    @XmlElement(name = "Prezime", required = true)
    protected String prezime;
    @XmlElement(name = "Email", required = true)
    protected String email;
    @XmlElement(name = "Sifra", required = true)
    protected String sifra;
    @XmlElement(name = "Uloga", required = true)
    protected String uloga;
    @XmlElement(name = "Adresa", required = true)
    protected Adresa adresa;

    public Korisnik(RegistrationDTO data) {
        this.ime = data.getIme();
        this.prezime = data.getPrezime();
        this.email = data.getEmail();
        this.sifra = data.getSifra();
        this.uloga = data.getUloga();
        this.adresa = new Adresa();
        this.adresa.setGrad(data.getGrad());
        this.adresa.setBroj(BigInteger.valueOf(data.getBroj()));
        this.adresa.setDrzava(data.getDrzava());
        this.adresa.setUlica(data.getUlica());
        this.adresa.setPostanskiBroj(BigInteger.valueOf(data.getPostanskiBroj()));
    }

    /**
     * Gets the value of the ime property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIme() {
        return ime;
    }

    /**
     * Sets the value of the ime property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIme(String value) {
        this.ime = value;
    }

    /**
     * Gets the value of the prezime property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPrezime() {
        return prezime;
    }

    /**
     * Sets the value of the prezime property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPrezime(String value) {
        this.prezime = value;
    }

    /**
     * Gets the value of the email property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the sifra property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSifra() {
        return sifra;
    }

    /**
     * Sets the value of the sifra property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSifra(String value) {
        this.sifra = value;
    }

    /**
     * Gets the value of the uloga property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUloga() {
        return uloga;
    }

    /**
     * Sets the value of the uloga property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUloga(String value) {
        this.uloga = value;
    }

    /**
     * Gets the value of the adresa property.
     *
     * @return possible object is
     * {@link Adresa }
     */
    public Adresa getAdresa() {
        return adresa;
    }

    /**
     * Sets the value of the adresa property.
     *
     * @param value allowed object is
     *              {@link Adresa }
     */
    public void setAdresa(Adresa value) {
        this.adresa = value;
    }

}
