//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.30 at 08:59:09 PM CET 
//


package ftn.xml.autor.model;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Vrsta" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Forma" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Podaci_o_naslovu_autorskog_dela" type="{http://www.ftn.uns.ac.rs/jaxb/autor}TZasnovanoDelo" minOccurs="0"/>
 *         &lt;element name="Stvoreno_u_radnom_odnosu" type="{http://www.ftn.uns.ac.rs/jaxb/autor}TEmpty" minOccurs="0"/>
 *         &lt;element name="Nacin_koriscenja" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "naslov",
    "vrsta",
    "forma",
    "podaciONaslovuAutorskogDela",
    "stvorenoURadnomOdnosu",
    "nacinKoriscenja"
})
@XmlRootElement(name = "AutorskoDelo")
public class AutorskoDelo {

    @XmlElement(name = "Naslov", required = true)
    protected String naslov;
    @XmlElement(name = "Vrsta", required = true)
    protected String vrsta;
    @XmlElement(name = "Forma", required = true)
    protected String forma;
    @XmlElement(name = "Podaci_o_naslovu_autorskog_dela")
    protected TZasnovanoDelo podaciONaslovuAutorskogDela;
    @XmlElement(name = "Stvoreno_u_radnom_odnosu")
    protected TEmpty stvorenoURadnomOdnosu;
    @XmlElement(name = "Nacin_koriscenja")
    protected String nacinKoriscenja;

    /**
     * Gets the value of the naslov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaslov() {
        return naslov;
    }

    /**
     * Sets the value of the naslov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaslov(String value) {
        this.naslov = value;
    }

    /**
     * Gets the value of the vrsta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVrsta() {
        return vrsta;
    }

    /**
     * Sets the value of the vrsta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVrsta(String value) {
        this.vrsta = value;
    }

    /**
     * Gets the value of the forma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForma() {
        return forma;
    }

    /**
     * Sets the value of the forma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForma(String value) {
        this.forma = value;
    }

    /**
     * Gets the value of the podaciONaslovuAutorskogDela property.
     * 
     * @return
     *     possible object is
     *     {@link TZasnovanoDelo }
     *     
     */
    public TZasnovanoDelo getPodaciONaslovuAutorskogDela() {
        return podaciONaslovuAutorskogDela;
    }

    /**
     * Sets the value of the podaciONaslovuAutorskogDela property.
     * 
     * @param value
     *     allowed object is
     *     {@link TZasnovanoDelo }
     *     
     */
    public void setPodaciONaslovuAutorskogDela(TZasnovanoDelo value) {
        this.podaciONaslovuAutorskogDela = value;
    }

    /**
     * Gets the value of the stvorenoURadnomOdnosu property.
     * 
     * @return
     *     possible object is
     *     {@link TEmpty }
     *     
     */
    public TEmpty getStvorenoURadnomOdnosu() {
        return stvorenoURadnomOdnosu;
    }

    /**
     * Sets the value of the stvorenoURadnomOdnosu property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEmpty }
     *     
     */
    public void setStvorenoURadnomOdnosu(TEmpty value) {
        this.stvorenoURadnomOdnosu = value;
    }

    /**
     * Gets the value of the nacinKoriscenja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNacinKoriscenja() {
        return nacinKoriscenja;
    }

    /**
     * Sets the value of the nacinKoriscenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNacinKoriscenja(String value) {
        this.nacinKoriscenja = value;
    }

}
