//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.13 at 06:10:09 PM CET 
//


package ftn.xml.autor.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.jaxb.autor package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.jaxb.autor
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZahtevZaIntelektualnuSvojinu }
     * 
     */
    public ZahtevZaIntelektualnuSvojinu createZahtevZaIntelektualnuSvojinu() {
        return new ZahtevZaIntelektualnuSvojinu();
    }

    /**
     * Create an instance of {@link ZahtevZaIntelektualnuSvojinu.PopunjavaPodnosilac }
     * 
     */
    public ZahtevZaIntelektualnuSvojinu.PopunjavaPodnosilac createZahtevZaIntelektualnuSvojinuPopunjavaPodnosilac() {
        return new ZahtevZaIntelektualnuSvojinu.PopunjavaPodnosilac();
    }

    /**
     * Create an instance of {@link ZahtevZaIntelektualnuSvojinu.PopunjavaZavod }
     * 
     */
    public ZahtevZaIntelektualnuSvojinu.PopunjavaZavod createZahtevZaIntelektualnuSvojinuPopunjavaZavod() {
        return new ZahtevZaIntelektualnuSvojinu.PopunjavaZavod();
    }

    /**
     * Create an instance of {@link TOpisDela }
     * 
     */
    public TOpisDela createTOpisDela() {
        return new TOpisDela();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link ZahtevZaIntelektualnuSvojinu.PopunjavaPodnosilac.Autori }
     * 
     */
    public ZahtevZaIntelektualnuSvojinu.PopunjavaPodnosilac.Autori createZahtevZaIntelektualnuSvojinuPopunjavaPodnosilacAutori() {
        return new ZahtevZaIntelektualnuSvojinu.PopunjavaPodnosilac.Autori();
    }

    /**
     * Create an instance of {@link TPoslovnoLice }
     * 
     */
    public TPoslovnoLice createTPoslovnoLice() {
        return new TPoslovnoLice();
    }

    /**
     * Create an instance of {@link TEmpty }
     * 
     */
    public TEmpty createTEmpty() {
        return new TEmpty();
    }

    /**
     * Create an instance of {@link Adresa }
     * 
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link ZahtevZaIntelektualnuSvojinu.InformacijaOUstanovi }
     * 
     */
    public ZahtevZaIntelektualnuSvojinu.InformacijaOUstanovi createZahtevZaIntelektualnuSvojinuInformacijaOUstanovi() {
        return new ZahtevZaIntelektualnuSvojinu.InformacijaOUstanovi();
    }

    /**
     * Create an instance of {@link ZahtevZaIntelektualnuSvojinu.PopunjavaZavod.PriloziUzZahtev }
     * 
     */
    public ZahtevZaIntelektualnuSvojinu.PopunjavaZavod.PriloziUzZahtev createZahtevZaIntelektualnuSvojinuPopunjavaZavodPriloziUzZahtev() {
        return new ZahtevZaIntelektualnuSvojinu.PopunjavaZavod.PriloziUzZahtev();
    }

    /**
     * Create an instance of {@link Kontakt }
     * 
     */
    public Kontakt createKontakt() {
        return new Kontakt();
    }

    /**
     * Create an instance of {@link AutorskoDelo }
     * 
     */
    public AutorskoDelo createAutorskoDelo() {
        return new AutorskoDelo();
    }

    /**
     * Create an instance of {@link TZasnovanoDelo }
     * 
     */
    public TZasnovanoDelo createTZasnovanoDelo() {
        return new TZasnovanoDelo();
    }

    /**
     * Create an instance of {@link TAutor }
     * 
     */
    public TAutor createTAutor() {
        return new TAutor();
    }

}
