//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.29 at 03:35:32 PM CET 
//


package ftn.xml.autor.model;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Popunjava_podnosilac">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Podnosilac" type="{http://www.ftn.uns.ac.rs/jaxb/autor}TLice"/>
 *                   &lt;element name="Punomocnik" type="{http://www.ftn.uns.ac.rs/jaxb/autor}TLice" minOccurs="0"/>
 *                   &lt;element name="Autori">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice maxOccurs="unbounded">
 *                             &lt;element name="Anoniman" type="{http://www.ftn.uns.ac.rs/jaxb/autor}TEmpty"/>
 *                             &lt;element name="Autor" type="{http://www.ftn.uns.ac.rs/jaxb/autor}TAutor"/>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element ref="{http://www.ftn.uns.ac.rs/jaxb/autor}AutorskoDelo"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Popunjava_zavod">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Broj_prijave">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="A-[0-9]{5}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Datum_podnosenja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Prilozi_uz_zahtev">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Opis_autorskog_dela" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Primer_autorskog_dela" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Dokaz_o_uplati_takse" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Izjava_o_pravno_osnovu_za_podnosenje_prijave" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Izjava_o_zajednickom_predstavniku" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Punomocje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Informacija_o_ustanovi">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ftn.uns.ac.rs/jaxb/autor}Adresa"/>
 *                   &lt;element name="Naziv">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "popunjavaPodnosilac",
    "popunjavaZavod",
    "priloziUzZahtev",
    "informacijaOUstanovi"
})
@XmlRootElement(name = "Zahtev_za_intelektualnu_svojinu")
public class ZahtevZaIntelektualnuSvojinu {

    @XmlElement(name = "Popunjava_podnosilac", required = true)
    protected PopunjavaPodnosilac popunjavaPodnosilac;
    @XmlElement(name = "Popunjava_zavod", required = true)
    protected PopunjavaZavod popunjavaZavod;
    @XmlElement(name = "Prilozi_uz_zahtev", required = true)
    protected PriloziUzZahtev priloziUzZahtev;
    @XmlElement(name = "Informacija_o_ustanovi", required = true)
    protected InformacijaOUstanovi informacijaOUstanovi;

    /**
     * Gets the value of the popunjavaPodnosilac property.
     * 
     * @return
     *     possible object is
     *     {@link PopunjavaPodnosilac }
     *     
     */
    public PopunjavaPodnosilac getPopunjavaPodnosilac() {
        return popunjavaPodnosilac;
    }

    /**
     * Sets the value of the popunjavaPodnosilac property.
     * 
     * @param value
     *     allowed object is
     *     {@link PopunjavaPodnosilac }
     *     
     */
    public void setPopunjavaPodnosilac(PopunjavaPodnosilac value) {
        this.popunjavaPodnosilac = value;
    }

    /**
     * Gets the value of the popunjavaZavod property.
     * 
     * @return
     *     possible object is
     *     {@link PopunjavaZavod }
     *     
     */
    public PopunjavaZavod getPopunjavaZavod() {
        return popunjavaZavod;
    }

    /**
     * Sets the value of the popunjavaZavod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PopunjavaZavod }
     *     
     */
    public void setPopunjavaZavod(PopunjavaZavod value) {
        this.popunjavaZavod = value;
    }

    /**
     * Gets the value of the priloziUzZahtev property.
     * 
     * @return
     *     possible object is
     *     {@link PriloziUzZahtev }
     *     
     */
    public PriloziUzZahtev getPriloziUzZahtev() {
        return priloziUzZahtev;
    }

    /**
     * Sets the value of the priloziUzZahtev property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriloziUzZahtev }
     *     
     */
    public void setPriloziUzZahtev(PriloziUzZahtev value) {
        this.priloziUzZahtev = value;
    }

    /**
     * Gets the value of the informacijaOUstanovi property.
     * 
     * @return
     *     possible object is
     *     {@link InformacijaOUstanovi }
     *     
     */
    public InformacijaOUstanovi getInformacijaOUstanovi() {
        return informacijaOUstanovi;
    }

    /**
     * Sets the value of the informacijaOUstanovi property.
     * 
     * @param value
     *     allowed object is
     *     {@link InformacijaOUstanovi }
     *     
     */
    public void setInformacijaOUstanovi(InformacijaOUstanovi value) {
        this.informacijaOUstanovi = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ftn.uns.ac.rs/jaxb/autor}Adresa"/>
     *         &lt;element name="Naziv">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "adresa",
        "naziv"
    })
    public static class InformacijaOUstanovi {

        @XmlElement(name = "Adresa", required = true)
        protected Adresa adresa;
        @XmlElement(name = "Naziv", required = true)
        protected String naziv;

        /**
         * Gets the value of the adresa property.
         * 
         * @return
         *     possible object is
         *     {@link Adresa }
         *     
         */
        public Adresa getAdresa() {
            return adresa;
        }

        /**
         * Sets the value of the adresa property.
         * 
         * @param value
         *     allowed object is
         *     {@link Adresa }
         *     
         */
        public void setAdresa(Adresa value) {
            this.adresa = value;
        }

        /**
         * Gets the value of the naziv property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaziv() {
            return naziv;
        }

        /**
         * Sets the value of the naziv property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaziv(String value) {
            this.naziv = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Podnosilac" type="{http://www.ftn.uns.ac.rs/jaxb/autor}TLice"/>
     *         &lt;element name="Punomocnik" type="{http://www.ftn.uns.ac.rs/jaxb/autor}TLice" minOccurs="0"/>
     *         &lt;element name="Autori">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice maxOccurs="unbounded">
     *                   &lt;element name="Anoniman" type="{http://www.ftn.uns.ac.rs/jaxb/autor}TEmpty"/>
     *                   &lt;element name="Autor" type="{http://www.ftn.uns.ac.rs/jaxb/autor}TAutor"/>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element ref="{http://www.ftn.uns.ac.rs/jaxb/autor}AutorskoDelo"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "podnosilac",
        "punomocnik",
        "autori",
        "autorskoDelo"
    })
    public static class PopunjavaPodnosilac {

        @XmlElement(name = "Podnosilac", required = true)
        protected TLice podnosilac;
        @XmlElement(name = "Punomocnik")
        protected TLice punomocnik;
        @XmlElement(name = "Autori", required = true)
        protected Autori autori;
        @XmlElement(name = "AutorskoDelo", required = true)
        protected AutorskoDelo autorskoDelo;

        /**
         * Gets the value of the podnosilac property.
         * 
         * @return
         *     possible object is
         *     {@link TLice }
         *     
         */
        public TLice getPodnosilac() {
            return podnosilac;
        }

        /**
         * Sets the value of the podnosilac property.
         * 
         * @param value
         *     allowed object is
         *     {@link TLice }
         *     
         */
        public void setPodnosilac(TLice value) {
            this.podnosilac = value;
        }

        /**
         * Gets the value of the punomocnik property.
         * 
         * @return
         *     possible object is
         *     {@link TLice }
         *     
         */
        public TLice getPunomocnik() {
            return punomocnik;
        }

        /**
         * Sets the value of the punomocnik property.
         * 
         * @param value
         *     allowed object is
         *     {@link TLice }
         *     
         */
        public void setPunomocnik(TLice value) {
            this.punomocnik = value;
        }

        /**
         * Gets the value of the autori property.
         * 
         * @return
         *     possible object is
         *     {@link Autori }
         *     
         */
        public Autori getAutori() {
            return autori;
        }

        /**
         * Sets the value of the autori property.
         * 
         * @param value
         *     allowed object is
         *     {@link Autori }
         *     
         */
        public void setAutori(Autori value) {
            this.autori = value;
        }

        /**
         * Gets the value of the autorskoDelo property.
         * 
         * @return
         *     possible object is
         *     {@link AutorskoDelo }
         *     
         */
        public AutorskoDelo getAutorskoDelo() {
            return autorskoDelo;
        }

        /**
         * Sets the value of the autorskoDelo property.
         * 
         * @param value
         *     allowed object is
         *     {@link AutorskoDelo }
         *     
         */
        public void setAutorskoDelo(AutorskoDelo value) {
            this.autorskoDelo = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice maxOccurs="unbounded">
         *         &lt;element name="Anoniman" type="{http://www.ftn.uns.ac.rs/jaxb/autor}TEmpty"/>
         *         &lt;element name="Autor" type="{http://www.ftn.uns.ac.rs/jaxb/autor}TAutor"/>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "anonimanOrAutor"
        })
        public static class Autori {

            @XmlElements({
                @XmlElement(name = "Autor", type = TAutor.class),
                @XmlElement(name = "Anoniman", type = TEmpty.class)
            })
            protected List<Object> anonimanOrAutor;

            /**
             * Gets the value of the anonimanOrAutor property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the anonimanOrAutor property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAnonimanOrAutor().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link TAutor }
             * {@link TEmpty }
             * 
             * 
             */
            public List<Object> getAnonimanOrAutor() {
                if (anonimanOrAutor == null) {
                    anonimanOrAutor = new ArrayList<Object>();
                }
                return this.anonimanOrAutor;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Broj_prijave">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="A-[0-9]{5}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Datum_podnosenja" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "brojPrijave",
        "datumPodnosenja"
    })
    public static class PopunjavaZavod {

        @XmlElement(name = "Broj_prijave", required = true)
        protected String brojPrijave;
        @XmlElement(name = "Datum_podnosenja", required = true)
        protected XMLGregorianCalendar datumPodnosenja;

        /**
         * Gets the value of the brojPrijave property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBrojPrijave() {
            return brojPrijave;
        }

        /**
         * Sets the value of the brojPrijave property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrojPrijave(String value) {
            this.brojPrijave = value;
        }

        /**
         * Gets the value of the datumPodnosenja property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumPodnosenja() {
            return datumPodnosenja;
        }

        /**
         * Sets the value of the datumPodnosenja property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumPodnosenja(XMLGregorianCalendar value) {
            this.datumPodnosenja = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Opis_autorskog_dela" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Primer_autorskog_dela" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Dokaz_o_uplati_takse" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Izjava_o_pravno_osnovu_za_podnosenje_prijave" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Izjava_o_zajednickom_predstavniku" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Punomocje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "opisAutorskogDela",
        "primerAutorskogDela",
        "dokazOUplatiTakse",
        "izjavaOPravnoOsnovuZaPodnosenjePrijave",
        "izjavaOZajednickomPredstavniku",
        "punomocje"
    })
    public static class PriloziUzZahtev {

        @XmlElement(name = "Opis_autorskog_dela", required = true)
        protected String opisAutorskogDela;
        @XmlElement(name = "Primer_autorskog_dela", required = true)
        protected String primerAutorskogDela;
        @XmlElement(name = "Dokaz_o_uplati_takse", required = true)
        protected String dokazOUplatiTakse;
        @XmlElement(name = "Izjava_o_pravno_osnovu_za_podnosenje_prijave")
        protected String izjavaOPravnoOsnovuZaPodnosenjePrijave;
        @XmlElement(name = "Izjava_o_zajednickom_predstavniku")
        protected String izjavaOZajednickomPredstavniku;
        @XmlElement(name = "Punomocje")
        protected String punomocje;

        /**
         * Gets the value of the opisAutorskogDela property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOpisAutorskogDela() {
            return opisAutorskogDela;
        }

        /**
         * Sets the value of the opisAutorskogDela property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOpisAutorskogDela(String value) {
            this.opisAutorskogDela = value;
        }

        /**
         * Gets the value of the primerAutorskogDela property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrimerAutorskogDela() {
            return primerAutorskogDela;
        }

        /**
         * Sets the value of the primerAutorskogDela property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrimerAutorskogDela(String value) {
            this.primerAutorskogDela = value;
        }

        /**
         * Gets the value of the dokazOUplatiTakse property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDokazOUplatiTakse() {
            return dokazOUplatiTakse;
        }

        /**
         * Sets the value of the dokazOUplatiTakse property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDokazOUplatiTakse(String value) {
            this.dokazOUplatiTakse = value;
        }

        /**
         * Gets the value of the izjavaOPravnoOsnovuZaPodnosenjePrijave property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIzjavaOPravnoOsnovuZaPodnosenjePrijave() {
            return izjavaOPravnoOsnovuZaPodnosenjePrijave;
        }

        /**
         * Sets the value of the izjavaOPravnoOsnovuZaPodnosenjePrijave property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIzjavaOPravnoOsnovuZaPodnosenjePrijave(String value) {
            this.izjavaOPravnoOsnovuZaPodnosenjePrijave = value;
        }

        /**
         * Gets the value of the izjavaOZajednickomPredstavniku property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIzjavaOZajednickomPredstavniku() {
            return izjavaOZajednickomPredstavniku;
        }

        /**
         * Sets the value of the izjavaOZajednickomPredstavniku property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIzjavaOZajednickomPredstavniku(String value) {
            this.izjavaOZajednickomPredstavniku = value;
        }

        /**
         * Gets the value of the punomocje property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPunomocje() {
            return punomocje;
        }

        /**
         * Sets the value of the punomocje property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPunomocje(String value) {
            this.punomocje = value;
        }

    }

}
