//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.01 at 11:50:59 PM CET 
//


package ftn.xml.autor.model.izvestaj;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Broj_odobrenih_zahteva">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Broj_odbijenih_zahteva">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Broj_podnetih_zahteva">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Naslov">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "brojOdobrenihZahteva",
    "brojOdbijenihZahteva",
    "brojPodnetihZahteva",
    "naslov"
})
@XmlRootElement(name = "Izvestaj")
public class Izvestaj {

    @XmlElement(name = "Broj_odobrenih_zahteva", required = true)
    protected String brojOdobrenihZahteva;
    @XmlElement(name = "Broj_odbijenih_zahteva", required = true)
    protected String brojOdbijenihZahteva;
    @XmlElement(name = "Broj_podnetih_zahteva", required = true)
    protected String brojPodnetihZahteva;
    @XmlElement(name = "Naslov", required = true)
    protected String naslov;

    /**
     * Gets the value of the brojOdobrenihZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojOdobrenihZahteva() {
        return brojOdobrenihZahteva;
    }

    /**
     * Sets the value of the brojOdobrenihZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojOdobrenihZahteva(String value) {
        this.brojOdobrenihZahteva = value;
    }

    /**
     * Gets the value of the brojOdbijenihZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojOdbijenihZahteva() {
        return brojOdbijenihZahteva;
    }

    /**
     * Sets the value of the brojOdbijenihZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojOdbijenihZahteva(String value) {
        this.brojOdbijenihZahteva = value;
    }

    /**
     * Gets the value of the brojPodnetihZahteva property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojPodnetihZahteva() {
        return brojPodnetihZahteva;
    }

    /**
     * Sets the value of the brojPodnetihZahteva property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojPodnetihZahteva(String value) {
        this.brojPodnetihZahteva = value;
    }

    /**
     * Gets the value of the naslov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaslov() {
        return naslov;
    }

    /**
     * Sets the value of the naslov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaslov(String value) {
        this.naslov = value;
    }

}
