//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.09 at 08:10:47 PM CET 
//


package ftn.xml.zig.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.jaxb.zig package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.jaxb.zig
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.PopunjavaPodnosilac }
     * 
     */
    public ZahtevZaPriznanjeZiga.PopunjavaPodnosilac createZahtevZaPriznanjeZigaPopunjavaPodnosilac() {
        return new ZahtevZaPriznanjeZiga.PopunjavaPodnosilac();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.PopunjavaPodnosilac.PlaceneTakse }
     * 
     */
    public ZahtevZaPriznanjeZiga.PopunjavaPodnosilac.PlaceneTakse createZahtevZaPriznanjeZigaPopunjavaPodnosilacPlaceneTakse() {
        return new ZahtevZaPriznanjeZiga.PopunjavaPodnosilac.PlaceneTakse();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.PopunjavaPodnosilac.Zig }
     * 
     */
    public ZahtevZaPriznanjeZiga.PopunjavaPodnosilac.Zig createZahtevZaPriznanjeZigaPopunjavaPodnosilacZig() {
        return new ZahtevZaPriznanjeZiga.PopunjavaPodnosilac.Zig();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.PopunjavaPodnosilac.Zig.Vrsta.TipA }
     * 
     */
    public ZahtevZaPriznanjeZiga.PopunjavaPodnosilac.Zig.Vrsta.TipA createZahtevZaPriznanjeZigaPopunjavaPodnosilacZigVrstaTipA() {
        return new ZahtevZaPriznanjeZiga.PopunjavaPodnosilac.Zig.Vrsta.TipA();
    }

    /**
     * Create an instance of {@link TPoslovnoLice }
     * 
     */
    public TPoslovnoLice createTPoslovnoLice() {
        return new TPoslovnoLice();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.InformacijeOUstanovi }
     * 
     */
    public ZahtevZaPriznanjeZiga.InformacijeOUstanovi createZahtevZaPriznanjeZigaInformacijeOUstanovi() {
        return new ZahtevZaPriznanjeZiga.InformacijeOUstanovi();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.PopunjavaPodnosilac.Zig.Vrsta.TipB }
     * 
     */
    public ZahtevZaPriznanjeZiga.PopunjavaPodnosilac.Zig.Vrsta.TipB createZahtevZaPriznanjeZigaPopunjavaPodnosilacZigVrstaTipB() {
        return new ZahtevZaPriznanjeZiga.PopunjavaPodnosilac.Zig.Vrsta.TipB();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.PopunjavaPodnosilac.DodatneInformacije }
     * 
     */
    public ZahtevZaPriznanjeZiga.PopunjavaPodnosilac.DodatneInformacije createZahtevZaPriznanjeZigaPopunjavaPodnosilacDodatneInformacije() {
        return new ZahtevZaPriznanjeZiga.PopunjavaPodnosilac.DodatneInformacije();
    }

    /**
     * Create an instance of {@link TEmpty }
     * 
     */
    public TEmpty createTEmpty() {
        return new TEmpty();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.PopunjavaPodnosilac.PlaceneTakse.ZaKlasa }
     * 
     */
    public ZahtevZaPriznanjeZiga.PopunjavaPodnosilac.PlaceneTakse.ZaKlasa createZahtevZaPriznanjeZigaPopunjavaPodnosilacPlaceneTakseZaKlasa() {
        return new ZahtevZaPriznanjeZiga.PopunjavaPodnosilac.PlaceneTakse.ZaKlasa();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.PopunjavaZavod }
     * 
     */
    public ZahtevZaPriznanjeZiga.PopunjavaZavod createZahtevZaPriznanjeZigaPopunjavaZavod() {
        return new ZahtevZaPriznanjeZiga.PopunjavaZavod();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.PopunjavaZavod.PriloziUzZahtev }
     * 
     */
    public ZahtevZaPriznanjeZiga.PopunjavaZavod.PriloziUzZahtev createZahtevZaPriznanjeZigaPopunjavaZavodPriloziUzZahtev() {
        return new ZahtevZaPriznanjeZiga.PopunjavaZavod.PriloziUzZahtev();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga }
     * 
     */
    public ZahtevZaPriznanjeZiga createZahtevZaPriznanjeZiga() {
        return new ZahtevZaPriznanjeZiga();
    }

    /**
     * Create an instance of {@link Adresa }
     * 
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.PopunjavaPodnosilac.DodatneInformacije.KlasaRobeIUslaga }
     * 
     */
    public ZahtevZaPriznanjeZiga.PopunjavaPodnosilac.DodatneInformacije.KlasaRobeIUslaga createZahtevZaPriznanjeZigaPopunjavaPodnosilacDodatneInformacijeKlasaRobeIUslaga() {
        return new ZahtevZaPriznanjeZiga.PopunjavaPodnosilac.DodatneInformacije.KlasaRobeIUslaga();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga.PopunjavaPodnosilac.Zig.Vrsta }
     * 
     */
    public ZahtevZaPriznanjeZiga.PopunjavaPodnosilac.Zig.Vrsta createZahtevZaPriznanjeZigaPopunjavaPodnosilacZigVrsta() {
        return new ZahtevZaPriznanjeZiga.PopunjavaPodnosilac.Zig.Vrsta();
    }

}
