//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.03 at 06:07:19 PM CET 
//


package ftn.xml.zig.model;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Informacije_o_ustanovi">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Naziv">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element ref="{http://www.ftn.uns.ac.rs/jaxb/zig}Adresa"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Broj_prijave_ziga">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="Z-[0-9]{5}/[0-9]{2}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Datum_podnosenja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Popunjava_podnosilac">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Podnosilac" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TLice"/>
 *                   &lt;element name="Punomocnik" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TLice" minOccurs="0"/>
 *                   &lt;element name="Zig">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Vrsta">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Tip_a">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;choice>
 *                                                 &lt;element name="Individualni_zig" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
 *                                                 &lt;element name="Kolektivni_zig" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
 *                                                 &lt;element name="Zig_garancije" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
 *                                               &lt;/choice>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="Tip_b">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;choice>
 *                                                 &lt;element name="Verbalni_znak" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
 *                                                 &lt;element name="Graficki_znak" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
 *                                                 &lt;element name="Kombinovani_znak" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
 *                                                 &lt;element name="Trodimenzionalni_znak" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
 *                                                 &lt;element name="Druga_vrsta" minOccurs="0">
 *                                                   &lt;simpleType>
 *                                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                       &lt;minLength value="1"/>
 *                                                       &lt;maxLength value="20"/>
 *                                                     &lt;/restriction>
 *                                                   &lt;/simpleType>
 *                                                 &lt;/element>
 *                                               &lt;/choice>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Naznacenje_boje">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Transliteracija_znak" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Prevod_znaka" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Opis_znaka" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Dodatne_informacije">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Klasa_robe_i_uslaga">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Klasa" maxOccurs="45">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *                                             &lt;maxInclusive value="45"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Zatrazeno_pravo_prvensta_i_osnov" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Placene_takse">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Osnovna_taksa" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                             &lt;element name="Za_klasa">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Naziv_klase" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Suma" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Za_graficko_resenje" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                             &lt;element name="Ukupno" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Prilozi_uz_zahtev">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="Primerak_znaka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Spisak_robe_i_usluga" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Punomocje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Opsti_akt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Dokaz_o_pravu_prvenstva" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Dokaz_o_uplati_takse" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="QR_kod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Resenje" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Datum" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="Status">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Odobren"/>
 *                         &lt;enumeration value="Odbijen"/>
 *                         &lt;enumeration value=""/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Ime">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Prezime">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Broj_prijave" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Referenca_na_zahtev" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Obrazlozenje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "informacijeOUstanovi",
    "brojPrijaveZiga",
    "datumPodnosenja",
    "popunjavaPodnosilac",
    "priloziUzZahtev",
    "qrKod",
    "resenje"
})
@XmlRootElement(name = "Zahtev_za_priznanje_ziga")
public class ZahtevZaPriznanjeZiga {

    @XmlElement(name = "Informacije_o_ustanovi", required = true)
    protected InformacijeOUstanovi informacijeOUstanovi;
    @XmlElement(name = "Broj_prijave_ziga", required = true)
    protected String brojPrijaveZiga;
    @XmlElement(name = "Datum_podnosenja", required = true)
    protected XMLGregorianCalendar datumPodnosenja;
    @XmlElement(name = "Popunjava_podnosilac", required = true)
    protected PopunjavaPodnosilac popunjavaPodnosilac;
    @XmlElement(name = "Prilozi_uz_zahtev", required = true)
    protected PriloziUzZahtev priloziUzZahtev;
    @XmlElement(name = "QR_kod", required = true)
    protected String qrKod;
    @XmlElement(name = "Resenje")
    protected Resenje resenje;

    /**
     * Gets the value of the informacijeOUstanovi property.
     * 
     * @return
     *     possible object is
     *     {@link InformacijeOUstanovi }
     *     
     */
    public InformacijeOUstanovi getInformacijeOUstanovi() {
        return informacijeOUstanovi;
    }

    /**
     * Sets the value of the informacijeOUstanovi property.
     * 
     * @param value
     *     allowed object is
     *     {@link InformacijeOUstanovi }
     *     
     */
    public void setInformacijeOUstanovi(InformacijeOUstanovi value) {
        this.informacijeOUstanovi = value;
    }

    /**
     * Gets the value of the brojPrijaveZiga property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojPrijaveZiga() {
        return brojPrijaveZiga;
    }

    /**
     * Sets the value of the brojPrijaveZiga property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojPrijaveZiga(String value) {
        this.brojPrijaveZiga = value;
    }

    /**
     * Gets the value of the datumPodnosenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPodnosenja() {
        return datumPodnosenja;
    }

    /**
     * Sets the value of the datumPodnosenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPodnosenja(XMLGregorianCalendar value) {
        this.datumPodnosenja = value;
    }

    /**
     * Gets the value of the popunjavaPodnosilac property.
     * 
     * @return
     *     possible object is
     *     {@link PopunjavaPodnosilac }
     *     
     */
    public PopunjavaPodnosilac getPopunjavaPodnosilac() {
        return popunjavaPodnosilac;
    }

    /**
     * Sets the value of the popunjavaPodnosilac property.
     * 
     * @param value
     *     allowed object is
     *     {@link PopunjavaPodnosilac }
     *     
     */
    public void setPopunjavaPodnosilac(PopunjavaPodnosilac value) {
        this.popunjavaPodnosilac = value;
    }

    /**
     * Gets the value of the priloziUzZahtev property.
     * 
     * @return
     *     possible object is
     *     {@link PriloziUzZahtev }
     *     
     */
    public PriloziUzZahtev getPriloziUzZahtev() {
        return priloziUzZahtev;
    }

    /**
     * Sets the value of the priloziUzZahtev property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriloziUzZahtev }
     *     
     */
    public void setPriloziUzZahtev(PriloziUzZahtev value) {
        this.priloziUzZahtev = value;
    }

    /**
     * Gets the value of the qrKod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQRKod() {
        return qrKod;
    }

    /**
     * Sets the value of the qrKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQRKod(String value) {
        this.qrKod = value;
    }

    /**
     * Gets the value of the resenje property.
     * 
     * @return
     *     possible object is
     *     {@link Resenje }
     *     
     */
    public Resenje getResenje() {
        return resenje;
    }

    /**
     * Sets the value of the resenje property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resenje }
     *     
     */
    public void setResenje(Resenje value) {
        this.resenje = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Naziv">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element ref="{http://www.ftn.uns.ac.rs/jaxb/zig}Adresa"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "naziv",
        "adresa"
    })
    public static class InformacijeOUstanovi {

        @XmlElement(name = "Naziv", required = true)
        protected String naziv;
        @XmlElement(name = "Adresa", required = true)
        protected Adresa adresa;

        /**
         * Gets the value of the naziv property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNaziv() {
            return naziv;
        }

        /**
         * Sets the value of the naziv property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNaziv(String value) {
            this.naziv = value;
        }

        /**
         * Gets the value of the adresa property.
         * 
         * @return
         *     possible object is
         *     {@link Adresa }
         *     
         */
        public Adresa getAdresa() {
            return adresa;
        }

        /**
         * Sets the value of the adresa property.
         * 
         * @param value
         *     allowed object is
         *     {@link Adresa }
         *     
         */
        public void setAdresa(Adresa value) {
            this.adresa = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Podnosilac" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TLice"/>
     *         &lt;element name="Punomocnik" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TLice" minOccurs="0"/>
     *         &lt;element name="Zig">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Vrsta">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Tip_a">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;choice>
     *                                       &lt;element name="Individualni_zig" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
     *                                       &lt;element name="Kolektivni_zig" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
     *                                       &lt;element name="Zig_garancije" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
     *                                     &lt;/choice>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="Tip_b">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;choice>
     *                                       &lt;element name="Verbalni_znak" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
     *                                       &lt;element name="Graficki_znak" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
     *                                       &lt;element name="Kombinovani_znak" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
     *                                       &lt;element name="Trodimenzionalni_znak" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
     *                                       &lt;element name="Druga_vrsta" minOccurs="0">
     *                                         &lt;simpleType>
     *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                             &lt;minLength value="1"/>
     *                                             &lt;maxLength value="20"/>
     *                                           &lt;/restriction>
     *                                         &lt;/simpleType>
     *                                       &lt;/element>
     *                                     &lt;/choice>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Naznacenje_boje">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Transliteracija_znak" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Prevod_znaka" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Opis_znaka" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Dodatne_informacije">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Klasa_robe_i_uslaga">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Klasa" maxOccurs="45">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
     *                                   &lt;maxInclusive value="45"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Zatrazeno_pravo_prvensta_i_osnov" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Placene_takse">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Osnovna_taksa" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *                   &lt;element name="Za_klasa">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Naziv_klase" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Suma" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Za_graficko_resenje" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *                   &lt;element name="Ukupno" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "podnosilac",
        "punomocnik",
        "zig",
        "dodatneInformacije",
        "placeneTakse"
    })
    public static class PopunjavaPodnosilac {

        @XmlElement(name = "Podnosilac", required = true)
        protected TLice podnosilac;
        @XmlElement(name = "Punomocnik")
        protected TLice punomocnik;
        @XmlElement(name = "Zig", required = true)
        protected Zig zig;
        @XmlElement(name = "Dodatne_informacije", required = true)
        protected DodatneInformacije dodatneInformacije;
        @XmlElement(name = "Placene_takse", required = true)
        protected PlaceneTakse placeneTakse;

        /**
         * Gets the value of the podnosilac property.
         * 
         * @return
         *     possible object is
         *     {@link TLice }
         *     
         */
        public TLice getPodnosilac() {
            return podnosilac;
        }

        /**
         * Sets the value of the podnosilac property.
         * 
         * @param value
         *     allowed object is
         *     {@link TLice }
         *     
         */
        public void setPodnosilac(TLice value) {
            this.podnosilac = value;
        }

        /**
         * Gets the value of the punomocnik property.
         * 
         * @return
         *     possible object is
         *     {@link TLice }
         *     
         */
        public TLice getPunomocnik() {
            return punomocnik;
        }

        /**
         * Sets the value of the punomocnik property.
         * 
         * @param value
         *     allowed object is
         *     {@link TLice }
         *     
         */
        public void setPunomocnik(TLice value) {
            this.punomocnik = value;
        }

        /**
         * Gets the value of the zig property.
         * 
         * @return
         *     possible object is
         *     {@link Zig }
         *     
         */
        public Zig getZig() {
            return zig;
        }

        /**
         * Sets the value of the zig property.
         * 
         * @param value
         *     allowed object is
         *     {@link Zig }
         *     
         */
        public void setZig(Zig value) {
            this.zig = value;
        }

        /**
         * Gets the value of the dodatneInformacije property.
         * 
         * @return
         *     possible object is
         *     {@link DodatneInformacije }
         *     
         */
        public DodatneInformacije getDodatneInformacije() {
            return dodatneInformacije;
        }

        /**
         * Sets the value of the dodatneInformacije property.
         * 
         * @param value
         *     allowed object is
         *     {@link DodatneInformacije }
         *     
         */
        public void setDodatneInformacije(DodatneInformacije value) {
            this.dodatneInformacije = value;
        }

        /**
         * Gets the value of the placeneTakse property.
         * 
         * @return
         *     possible object is
         *     {@link PlaceneTakse }
         *     
         */
        public PlaceneTakse getPlaceneTakse() {
            return placeneTakse;
        }

        /**
         * Sets the value of the placeneTakse property.
         * 
         * @param value
         *     allowed object is
         *     {@link PlaceneTakse }
         *     
         */
        public void setPlaceneTakse(PlaceneTakse value) {
            this.placeneTakse = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Klasa_robe_i_uslaga">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Klasa" maxOccurs="45">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
         *                         &lt;maxInclusive value="45"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Zatrazeno_pravo_prvensta_i_osnov" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "klasaRobeIUslaga",
            "zatrazenoPravoPrvenstaIOsnov"
        })
        public static class DodatneInformacije {

            @XmlElement(name = "Klasa_robe_i_uslaga", required = true)
            protected KlasaRobeIUslaga klasaRobeIUslaga;
            @XmlElement(name = "Zatrazeno_pravo_prvensta_i_osnov", required = true)
            protected String zatrazenoPravoPrvenstaIOsnov;

            /**
             * Gets the value of the klasaRobeIUslaga property.
             * 
             * @return
             *     possible object is
             *     {@link KlasaRobeIUslaga }
             *     
             */
            public KlasaRobeIUslaga getKlasaRobeIUslaga() {
                return klasaRobeIUslaga;
            }

            /**
             * Sets the value of the klasaRobeIUslaga property.
             * 
             * @param value
             *     allowed object is
             *     {@link KlasaRobeIUslaga }
             *     
             */
            public void setKlasaRobeIUslaga(KlasaRobeIUslaga value) {
                this.klasaRobeIUslaga = value;
            }

            /**
             * Gets the value of the zatrazenoPravoPrvenstaIOsnov property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZatrazenoPravoPrvenstaIOsnov() {
                return zatrazenoPravoPrvenstaIOsnov;
            }

            /**
             * Sets the value of the zatrazenoPravoPrvenstaIOsnov property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZatrazenoPravoPrvenstaIOsnov(String value) {
                this.zatrazenoPravoPrvenstaIOsnov = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Klasa" maxOccurs="45">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
             *               &lt;maxInclusive value="45"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "klasa"
            })
            public static class KlasaRobeIUslaga {

                @XmlElement(name = "Klasa", type = Integer.class)
                protected List<Integer> klasa;

                /**
                 * Gets the value of the klasa property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the klasa property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getKlasa().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Integer }
                 * 
                 * 
                 */
                public List<Integer> getKlasa() {
                    if (klasa == null) {
                        klasa = new ArrayList<Integer>();
                    }
                    return this.klasa;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Osnovna_taksa" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
         *         &lt;element name="Za_klasa">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Naziv_klase" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Suma" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Za_graficko_resenje" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
         *         &lt;element name="Ukupno" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "osnovnaTaksa",
            "zaKlasa",
            "zaGrafickoResenje",
            "ukupno"
        })
        public static class PlaceneTakse {

            @XmlElement(name = "Osnovna_taksa", required = true)
            protected BigInteger osnovnaTaksa;
            @XmlElement(name = "Za_klasa", required = true)
            protected ZaKlasa zaKlasa;
            @XmlElement(name = "Za_graficko_resenje", required = true)
            protected BigInteger zaGrafickoResenje;
            @XmlElement(name = "Ukupno", required = true)
            protected BigInteger ukupno;

            /**
             * Gets the value of the osnovnaTaksa property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getOsnovnaTaksa() {
                return osnovnaTaksa;
            }

            /**
             * Sets the value of the osnovnaTaksa property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setOsnovnaTaksa(BigInteger value) {
                this.osnovnaTaksa = value;
            }

            /**
             * Gets the value of the zaKlasa property.
             * 
             * @return
             *     possible object is
             *     {@link ZaKlasa }
             *     
             */
            public ZaKlasa getZaKlasa() {
                return zaKlasa;
            }

            /**
             * Sets the value of the zaKlasa property.
             * 
             * @param value
             *     allowed object is
             *     {@link ZaKlasa }
             *     
             */
            public void setZaKlasa(ZaKlasa value) {
                this.zaKlasa = value;
            }

            /**
             * Gets the value of the zaGrafickoResenje property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getZaGrafickoResenje() {
                return zaGrafickoResenje;
            }

            /**
             * Sets the value of the zaGrafickoResenje property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setZaGrafickoResenje(BigInteger value) {
                this.zaGrafickoResenje = value;
            }

            /**
             * Gets the value of the ukupno property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getUkupno() {
                return ukupno;
            }

            /**
             * Sets the value of the ukupno property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setUkupno(BigInteger value) {
                this.ukupno = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Naziv_klase" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Suma" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "nazivKlase",
                "suma"
            })
            public static class ZaKlasa {

                @XmlElement(name = "Naziv_klase", required = true)
                protected String nazivKlase;
                @XmlElement(name = "Suma", required = true)
                protected BigInteger suma;

                /**
                 * Gets the value of the nazivKlase property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNazivKlase() {
                    return nazivKlase;
                }

                /**
                 * Sets the value of the nazivKlase property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNazivKlase(String value) {
                    this.nazivKlase = value;
                }

                /**
                 * Gets the value of the suma property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getSuma() {
                    return suma;
                }

                /**
                 * Sets the value of the suma property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setSuma(BigInteger value) {
                    this.suma = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Vrsta">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Tip_a">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;choice>
         *                             &lt;element name="Individualni_zig" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
         *                             &lt;element name="Kolektivni_zig" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
         *                             &lt;element name="Zig_garancije" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
         *                           &lt;/choice>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="Tip_b">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;choice>
         *                             &lt;element name="Verbalni_znak" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
         *                             &lt;element name="Graficki_znak" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
         *                             &lt;element name="Kombinovani_znak" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
         *                             &lt;element name="Trodimenzionalni_znak" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
         *                             &lt;element name="Druga_vrsta" minOccurs="0">
         *                               &lt;simpleType>
         *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                                   &lt;minLength value="1"/>
         *                                   &lt;maxLength value="20"/>
         *                                 &lt;/restriction>
         *                               &lt;/simpleType>
         *                             &lt;/element>
         *                           &lt;/choice>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Naznacenje_boje">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Transliteracija_znak" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Prevod_znaka" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Opis_znaka" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "vrsta",
            "naznacenjeBoje",
            "transliteracijaZnak",
            "prevodZnaka",
            "opisZnaka"
        })
        public static class Zig {

            @XmlElement(name = "Vrsta", required = true)
            protected Vrsta vrsta;
            @XmlElement(name = "Naznacenje_boje", required = true)
            protected String naznacenjeBoje;
            @XmlElement(name = "Transliteracija_znak")
            protected String transliteracijaZnak;
            @XmlElement(name = "Prevod_znaka")
            protected String prevodZnaka;
            @XmlElement(name = "Opis_znaka")
            protected String opisZnaka;

            /**
             * Gets the value of the vrsta property.
             * 
             * @return
             *     possible object is
             *     {@link Vrsta }
             *     
             */
            public Vrsta getVrsta() {
                return vrsta;
            }

            /**
             * Sets the value of the vrsta property.
             * 
             * @param value
             *     allowed object is
             *     {@link Vrsta }
             *     
             */
            public void setVrsta(Vrsta value) {
                this.vrsta = value;
            }

            /**
             * Gets the value of the naznacenjeBoje property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNaznacenjeBoje() {
                return naznacenjeBoje;
            }

            /**
             * Sets the value of the naznacenjeBoje property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNaznacenjeBoje(String value) {
                this.naznacenjeBoje = value;
            }

            /**
             * Gets the value of the transliteracijaZnak property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTransliteracijaZnak() {
                return transliteracijaZnak;
            }

            /**
             * Sets the value of the transliteracijaZnak property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTransliteracijaZnak(String value) {
                this.transliteracijaZnak = value;
            }

            /**
             * Gets the value of the prevodZnaka property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrevodZnaka() {
                return prevodZnaka;
            }

            /**
             * Sets the value of the prevodZnaka property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrevodZnaka(String value) {
                this.prevodZnaka = value;
            }

            /**
             * Gets the value of the opisZnaka property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOpisZnaka() {
                return opisZnaka;
            }

            /**
             * Sets the value of the opisZnaka property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOpisZnaka(String value) {
                this.opisZnaka = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Tip_a">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;choice>
             *                   &lt;element name="Individualni_zig" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
             *                   &lt;element name="Kolektivni_zig" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
             *                   &lt;element name="Zig_garancije" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
             *                 &lt;/choice>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="Tip_b">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;choice>
             *                   &lt;element name="Verbalni_znak" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
             *                   &lt;element name="Graficki_znak" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
             *                   &lt;element name="Kombinovani_znak" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
             *                   &lt;element name="Trodimenzionalni_znak" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
             *                   &lt;element name="Druga_vrsta" minOccurs="0">
             *                     &lt;simpleType>
             *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *                         &lt;minLength value="1"/>
             *                         &lt;maxLength value="20"/>
             *                       &lt;/restriction>
             *                     &lt;/simpleType>
             *                   &lt;/element>
             *                 &lt;/choice>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "tipA",
                "tipB"
            })
            public static class Vrsta {

                @XmlElement(name = "Tip_a", required = true)
                protected TipA tipA;
                @XmlElement(name = "Tip_b", required = true)
                protected TipB tipB;

                /**
                 * Gets the value of the tipA property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TipA }
                 *     
                 */
                public TipA getTipA() {
                    return tipA;
                }

                /**
                 * Sets the value of the tipA property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TipA }
                 *     
                 */
                public void setTipA(TipA value) {
                    this.tipA = value;
                }

                /**
                 * Gets the value of the tipB property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TipB }
                 *     
                 */
                public TipB getTipB() {
                    return tipB;
                }

                /**
                 * Sets the value of the tipB property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TipB }
                 *     
                 */
                public void setTipB(TipB value) {
                    this.tipB = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;choice>
                 *         &lt;element name="Individualni_zig" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
                 *         &lt;element name="Kolektivni_zig" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
                 *         &lt;element name="Zig_garancije" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
                 *       &lt;/choice>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "individualniZig",
                    "kolektivniZig",
                    "zigGarancije"
                })
                public static class TipA {

                    @XmlElement(name = "Individualni_zig")
                    protected TEmpty individualniZig;
                    @XmlElement(name = "Kolektivni_zig")
                    protected TEmpty kolektivniZig;
                    @XmlElement(name = "Zig_garancije")
                    protected TEmpty zigGarancije;

                    /**
                     * Gets the value of the individualniZig property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link TEmpty }
                     *     
                     */
                    public TEmpty getIndividualniZig() {
                        return individualniZig;
                    }

                    /**
                     * Sets the value of the individualniZig property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link TEmpty }
                     *     
                     */
                    public void setIndividualniZig(TEmpty value) {
                        this.individualniZig = value;
                    }

                    /**
                     * Gets the value of the kolektivniZig property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link TEmpty }
                     *     
                     */
                    public TEmpty getKolektivniZig() {
                        return kolektivniZig;
                    }

                    /**
                     * Sets the value of the kolektivniZig property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link TEmpty }
                     *     
                     */
                    public void setKolektivniZig(TEmpty value) {
                        this.kolektivniZig = value;
                    }

                    /**
                     * Gets the value of the zigGarancije property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link TEmpty }
                     *     
                     */
                    public TEmpty getZigGarancije() {
                        return zigGarancije;
                    }

                    /**
                     * Sets the value of the zigGarancije property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link TEmpty }
                     *     
                     */
                    public void setZigGarancije(TEmpty value) {
                        this.zigGarancije = value;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;choice>
                 *         &lt;element name="Verbalni_znak" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
                 *         &lt;element name="Graficki_znak" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
                 *         &lt;element name="Kombinovani_znak" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
                 *         &lt;element name="Trodimenzionalni_znak" type="{http://www.ftn.uns.ac.rs/jaxb/zig}TEmpty" minOccurs="0"/>
                 *         &lt;element name="Druga_vrsta" minOccurs="0">
                 *           &lt;simpleType>
                 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
                 *               &lt;minLength value="1"/>
                 *               &lt;maxLength value="20"/>
                 *             &lt;/restriction>
                 *           &lt;/simpleType>
                 *         &lt;/element>
                 *       &lt;/choice>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "verbalniZnak",
                    "grafickiZnak",
                    "kombinovaniZnak",
                    "trodimenzionalniZnak",
                    "drugaVrsta"
                })
                public static class TipB {

                    @XmlElement(name = "Verbalni_znak")
                    protected TEmpty verbalniZnak;
                    @XmlElement(name = "Graficki_znak")
                    protected TEmpty grafickiZnak;
                    @XmlElement(name = "Kombinovani_znak")
                    protected TEmpty kombinovaniZnak;
                    @XmlElement(name = "Trodimenzionalni_znak")
                    protected TEmpty trodimenzionalniZnak;
                    @XmlElement(name = "Druga_vrsta")
                    protected String drugaVrsta;

                    /**
                     * Gets the value of the verbalniZnak property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link TEmpty }
                     *     
                     */
                    public TEmpty getVerbalniZnak() {
                        return verbalniZnak;
                    }

                    /**
                     * Sets the value of the verbalniZnak property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link TEmpty }
                     *     
                     */
                    public void setVerbalniZnak(TEmpty value) {
                        this.verbalniZnak = value;
                    }

                    /**
                     * Gets the value of the grafickiZnak property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link TEmpty }
                     *     
                     */
                    public TEmpty getGrafickiZnak() {
                        return grafickiZnak;
                    }

                    /**
                     * Sets the value of the grafickiZnak property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link TEmpty }
                     *     
                     */
                    public void setGrafickiZnak(TEmpty value) {
                        this.grafickiZnak = value;
                    }

                    /**
                     * Gets the value of the kombinovaniZnak property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link TEmpty }
                     *     
                     */
                    public TEmpty getKombinovaniZnak() {
                        return kombinovaniZnak;
                    }

                    /**
                     * Sets the value of the kombinovaniZnak property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link TEmpty }
                     *     
                     */
                    public void setKombinovaniZnak(TEmpty value) {
                        this.kombinovaniZnak = value;
                    }

                    /**
                     * Gets the value of the trodimenzionalniZnak property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link TEmpty }
                     *     
                     */
                    public TEmpty getTrodimenzionalniZnak() {
                        return trodimenzionalniZnak;
                    }

                    /**
                     * Sets the value of the trodimenzionalniZnak property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link TEmpty }
                     *     
                     */
                    public void setTrodimenzionalniZnak(TEmpty value) {
                        this.trodimenzionalniZnak = value;
                    }

                    /**
                     * Gets the value of the drugaVrsta property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getDrugaVrsta() {
                        return drugaVrsta;
                    }

                    /**
                     * Sets the value of the drugaVrsta property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setDrugaVrsta(String value) {
                        this.drugaVrsta = value;
                    }

                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="Primerak_znaka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Spisak_robe_i_usluga" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Punomocje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Opsti_akt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Dokaz_o_pravu_prvenstva" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Dokaz_o_uplati_takse" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class PriloziUzZahtev {

        @XmlElement(name = "Primerak_znaka")
        protected String primerakZnaka;
        @XmlElement(name = "Spisak_robe_i_usluga")
        protected String spisakRobeIUsluga;
        @XmlElement(name = "Punomocje")
        protected String punomocje;
        @XmlElement(name = "Opsti_akt")
        protected String opstiAkt;
        @XmlElement(name = "Dokaz_o_pravu_prvenstva")
        protected String dokazOPravuPrvenstva;
        @XmlElement(name = "Dokaz_o_uplati_takse")
        protected String dokazOUplatiTakse;

        /**
         * Gets the value of the primerakZnaka property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrimerakZnaka() {
            return primerakZnaka;
        }

        /**
         * Sets the value of the primerakZnaka property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrimerakZnaka(String value) {
            this.primerakZnaka = value;
        }

        /**
         * Gets the value of the spisakRobeIUsluga property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpisakRobeIUsluga() {
            return spisakRobeIUsluga;
        }

        /**
         * Sets the value of the spisakRobeIUsluga property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpisakRobeIUsluga(String value) {
            this.spisakRobeIUsluga = value;
        }

        /**
         * Gets the value of the punomocje property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPunomocje() {
            return punomocje;
        }

        /**
         * Sets the value of the punomocje property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPunomocje(String value) {
            this.punomocje = value;
        }

        /**
         * Gets the value of the opstiAkt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOpstiAkt() {
            return opstiAkt;
        }

        /**
         * Sets the value of the opstiAkt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOpstiAkt(String value) {
            this.opstiAkt = value;
        }

        /**
         * Gets the value of the dokazOPravuPrvenstva property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDokazOPravuPrvenstva() {
            return dokazOPravuPrvenstva;
        }

        /**
         * Sets the value of the dokazOPravuPrvenstva property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDokazOPravuPrvenstva(String value) {
            this.dokazOPravuPrvenstva = value;
        }

        /**
         * Gets the value of the dokazOUplatiTakse property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDokazOUplatiTakse() {
            return dokazOUplatiTakse;
        }

        /**
         * Sets the value of the dokazOUplatiTakse property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDokazOUplatiTakse(String value) {
            this.dokazOUplatiTakse = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Datum" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="Status">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Odobren"/>
     *               &lt;enumeration value="Odbijen"/>
     *               &lt;enumeration value=""/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Ime">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Prezime">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Broj_prijave" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Referenca_na_zahtev" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Obrazlozenje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "datum",
        "status",
        "ime",
        "prezime",
        "brojPrijave",
        "referencaNaZahtev",
        "obrazlozenje"
    })
    public static class Resenje {

        @XmlElement(name = "Datum", required = true)
        protected XMLGregorianCalendar datum;
        @XmlElement(name = "Status", required = true)
        protected String status;
        @XmlElement(name = "Ime", required = true)
        protected String ime;
        @XmlElement(name = "Prezime", required = true)
        protected String prezime;
        @XmlElement(name = "Broj_prijave", required = true)
        protected String brojPrijave;
        @XmlElement(name = "Referenca_na_zahtev", required = true)
        protected String referencaNaZahtev;
        @XmlElement(name = "Obrazlozenje")
        protected String obrazlozenje;

        /**
         * Gets the value of the datum property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatum() {
            return datum;
        }

        /**
         * Sets the value of the datum property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatum(XMLGregorianCalendar value) {
            this.datum = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the ime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIme() {
            return ime;
        }

        /**
         * Sets the value of the ime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIme(String value) {
            this.ime = value;
        }

        /**
         * Gets the value of the prezime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrezime() {
            return prezime;
        }

        /**
         * Sets the value of the prezime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrezime(String value) {
            this.prezime = value;
        }

        /**
         * Gets the value of the brojPrijave property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBrojPrijave() {
            return brojPrijave;
        }

        /**
         * Sets the value of the brojPrijave property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrojPrijave(String value) {
            this.brojPrijave = value;
        }

        /**
         * Gets the value of the referencaNaZahtev property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReferencaNaZahtev() {
            return referencaNaZahtev;
        }

        /**
         * Sets the value of the referencaNaZahtev property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReferencaNaZahtev(String value) {
            this.referencaNaZahtev = value;
        }

        /**
         * Gets the value of the obrazlozenje property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getObrazlozenje() {
            return obrazlozenje;
        }

        /**
         * Sets the value of the obrazlozenje property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setObrazlozenje(String value) {
            this.obrazlozenje = value;
        }

    }

}
